/*
File: iAd.Ext.js

Abstract: iAd JS Extensions JS. 

Version: 1.2.0-stage

Disclaimer: IMPORTANT:  This Apple software is supplied to you by Apple 
Inc. ("Apple") in consideration of your agreement to the following 
terms, and your use, installation, modification or redistribution of 
this Apple software constitutes acceptance of these terms.  If you do 
not agree with these terms, please do not use, install, modify or 
redistribute this Apple software. 

In consideration of your agreement to abide by the following terms, and 
subject to these terms, Apple grants you a personal, non-exclusive 
license, under Apple's copyrights in this original Apple software (the 
"Apple Software"), to use, reproduce, modify and redistribute the Apple 
Software, with or without modifications, in source and/or binary forms; 
provided that if you redistribute the Apple Software in its entirety and 
without modifications, you must retain this notice and the following 
text and disclaimers in all such redistributions of the Apple Software. 
Neither the name, trademarks, service marks or logos of Apple Inc. may 
be used to endorse or promote products derived from the Apple Software 
without specific prior written permission from Apple.  Except as 
expressly stated in this notice, no other rights or licenses, express or 
implied, are granted by Apple herein, including but not limited to any 
patent rights that may be infringed by your derivative works or by other 
works in which the Apple Software may be incorporated. 

The Apple Software is provided by Apple on an "AS IS" basis.  APPLE 
MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION 
THE IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS 
FOR A PARTICULAR PURPOSE, REGARDING THE APPLE SOFTWARE OR ITS USE AND 
OPERATION ALONE OR IN COMBINATION WITH YOUR PRODUCTS. 

IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL 
OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) ARISING IN ANY WAY OUT OF THE USE, REPRODUCTION, 
MODIFICATION AND/OR DISTRIBUTION OF THE APPLE SOFTWARE, HOWEVER CAUSED 
AND WHETHER UNDER THEORY OF CONTRACT, TORT (INCLUDING NEGLIGENCE), 
STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN ADVISED OF THE 
POSSIBILITY OF SUCH DAMAGE. 

Copyright (C) 2012 Apple Inc. All Rights Reserved. 

*/

iAd.Ext={};iAd.Ext.VERSION="1.2.0-stage";iAd.Ext.IS_IN_ADSHEET=window.hasOwnProperty("ad");iAd.Ext.DEVICE_PATH=iAd.Device.IS_IPAD?"ipad/":"iphone/";iAd.Ext.CSS_PATH="css/"+iAd.Ext.DEVICE_PATH;iAd.Ext.ASSET_PATH="assets/"+iAd.Ext.DEVICE_PATH;iAd.Ext.TimerStrategy={};iAd.Ext.TimerStrategy.CancelOnTouchStart={handleTouchStart:function(a){a.timer.stop();a.releaseTimer()},handleViewWillDisappear:function(a){a.timer.stop();a.releaseTimer()}};
iAd.Ext.TimerStrategy.CancelOnTouchStartAndWhenViewDisappears=iAd.Ext.TimerStrategy.CancelOnTouchStart;iAd.Ext.TimerStrategy.CancelOnTouchStartInAnyView={appliesToRootView:true};iAd.Utils.copyPropertiesFromSourceToTarget(iAd.Ext.TimerStrategy.CancelOnTouchStart,iAd.Ext.TimerStrategy.CancelOnTouchStartInAnyView);iAd.Ext.TimerStrategy.CancelOnTouchStartInAnyViewAndWhenViewDisappears=iAd.Ext.TimerStrategy.CancelOnTouchStartInAnyView;
iAd.Ext.TimerStrategy.RestartOnTouchStart={handleTouchStart:function(a){a.timer.restartAllPendingTimers()},handleViewWillDisappear:function(a){a.timer.stop();a.releaseTimer()}};iAd.Ext.TimerStrategy.RescheduleOnTouchStartAndCancelWhenViewDisappears=iAd.Ext.TimerStrategy.RestartOnTouchStart;iAd.Ext.TimerStrategy.RestartOnTouchStartInAnyView={appliesToRootView:true};iAd.Utils.copyPropertiesFromSourceToTarget(iAd.Ext.TimerStrategy.RestartOnTouchStart,iAd.Ext.TimerStrategy.RestartOnTouchStartInAnyView);
iAd.Ext.TimerStrategy.RescheduleOnTouchStartInAnyViewAndCancelWhenViewDisappears=iAd.Ext.TimerStrategy.RestartOnTouchStartInAnyView;iAd.Class({name:"iAd.Ext.MapAnnotation",synthesizedProperties:["formattedAnnotation"]});iAd.Ext.MapAnnotation.PIN_COLOR_RED="red";iAd.Ext.MapAnnotation.PIN_COLOR_GREEN="green";iAd.Ext.MapAnnotation.PIN_COLOR_PURPLE="purple";
iAd.Ext.MapAnnotation.prototype.init=function(a){this.callSuper();this._formattedAnnotation=null;this.latitude=a.latitude;this.longitude=a.longitude;this.identifier=a.identifier.toString();this.pinColor=a.pinColor||iAd.Ext.MapAnnotation.PIN_COLOR_RED;this.imageURL=a.imageURL?iAd.Path.resolveAbsolutePath(iAd.Ext.ASSET_PATH+a.imageURL):null;this.xOffset=a.xOffset;this.yOffset=a.yOffset;this.title=a.title||"";this.subtitle=a.subtitle||"";this.hasLeftCalloutButton=a.hasLeftCalloutButton===void 0||!!a.hasLeftCalloutButton;
this.hasRightCalloutButton=a.hasRightCalloutButton||false};iAd.Ext.MapAnnotation.prototype.getFormattedAnnotation=function(){return{latitude:this.latitude,longitude:this.longitude,identifier:this.identifier,pinColor:this.pinColor,imageURL:this.imageURL,xOffset:this.xOffset,yOffset:this.yOffset,title:this.title,subtitle:this.subtitle,hasLeftCalloutButton:this.hasLeftCalloutButton,hasRightCalloutButton:this.hasRightCalloutButton}};
iAd.Ext.MapAnnotation.annotationFromLocation=function(a){return{latitude:a.loc.latitude,longitude:a.loc.longitude,identifier:a.id,title:"",subtitle:"",pinColor:"",imageURL:null,xOffset:"",yOffset:"",hasLeftCalloutButton:true,hasRightCalloutButton:false}};iAd.Ext.MapAnnotation.createAnnotationForMap=function(a){return new (!iAd.Ext.IS_IN_ADSHEET?iAd.Ext.MapAnnotation:iAd.Ext.Map.SUPPORTS_MAP_PLUGIN?iAd.Ext.MapAnnotation:iAd.Ext.LegacyMapAnnotation)(a)};
iAd.Class({name:"iAd.Ext.ImageViewProcessor",superclass:iAd.ViewProcessor});iAd.Ext.ImageViewProcessor.prototype.init=function(a){this.callSuper(a);this.processedImages=[]};iAd.Ext.ImageViewProcessor.IMAGE_SRC="ad-ext-image-src";iAd.Ext.ImageViewProcessor.LOCALIZED_IMAGE="ad-ext-localized-image";iAd.Ext.ImageViewProcessor.IMAGE_SRC_DEVICE=iAd.Device.IS_IPAD?"ad-ext-image-src-ipad":"ad-ext-image-src-iphone";
iAd.Ext.ImageViewProcessor.prototype.processView=function(a){this.callSuper(a);for(var b=iAd.Ext.ImageViewProcessor.IMAGE_SRC,c=iAd.Element.HTML5_CUSTOM_ATTRIBUTE_PREFIX+iAd.Ext.ImageViewProcessor.IMAGE_SRC_DEVICE,d=iAd.Element.HTML5_CUSTOM_ATTRIBUTE_PREFIX+iAd.Ext.ImageViewProcessor.LOCALIZED_IMAGE,a=a.layer.querySelectorAll("["+(iAd.Element.HTML5_CUSTOM_ATTRIBUTE_PREFIX+b)+"],["+b+"],["+c+"]"),e=0,g=a.length;e<g;e++){var f=a[e];if(!f.hasOwnProperty("_adProcessedImage")){var h=iAd.Element.getCustomAttribute(f,
b)||iAd.Element.getCustomAttribute(f,c);iAd.Element.hasCustomAttribute(f,d)&&(h=iAd.Ext.Utils.appendLocalizationCodeSuffix(h));if(f.nodeName=="IMG")f.src=h?this.resolveImagePath(h):"";else{for(var h=h.split(/\s*,\s*/),i=[],j;j=h.shift();)i.push('url(" '+this.resolveImagePath(j)+' ")');background_image_src=i.join(",");f.style.backgroundImage=background_image_src}f._adProcessedImage=true;this.processedImages.push(f)}}};
iAd.Ext.ImageViewProcessor.prototype.resolveImagePath=function(a){return iAd.Device.HAS_HIDPI_DISPLAY?iAd.Ext.ASSET_PATH+iAd.Path.appendHiDPISuffix(a):iAd.Ext.ASSET_PATH+a};iAd.Ext.ImageViewProcessor.prototype.cleanUp=function(){this.callSuper();for(var a;a=this.processedImages.pop();)delete a._adProcessedImage};iAd.ViewController.addViewProcessor(iAd.Ext.ImageViewProcessor);iAd.Ext.Utils=iAd.Ext.Utils||{};iAd.Ext.Utils.clampNegativeValue=iAd.Utils.clampNegativeValue||function(a,b){return a<0?b:a};
iAd.Ext.Utils.appendLocalizationCodeSuffix=function(a){iAd.RootViewController.sharedRootViewController.config.locale||iAd.Console.error("[iAd.Ext.Utils.appendLocalizationCodeSuffix] iAd.RootViewController.sharedRootViewController.config.locale does not exist.");return iAd.Ext.Utils.appendSuffixToPath(a,"_"+iAd.RootViewController.sharedRootViewController.config.locale)};
iAd.Ext.Utils.appendSuffixToPath=function(a,b){if(!a)return"";if(!b)return a;for(var c=a.length;c;){--c;if(a[c]==="/")break;if(a[c]===".")return a.substr(0,c)+b+a.substr(c)}return a+b};iAd.Ext.Utils.centerViewWithRespectToView=function(a,b){var c=a.size,d=b.size;a.position=new iAd.Point((d.width-c.width)/2,(d.height-c.height)/2)};iAd.Class({name:"iAd.Ext.Timer",mixins:[iAd.EventTarget]});iAd.Ext.Timer.MINIMUM_TIMER_INTERVAL=1;iAd.Ext.Timer.TIMER_FIRED_EVENT="timerFired";
iAd.Ext.Timer.prototype.init=function(a){this.callSuper();this._timerFiredFunction=null;this._timers=[];this._isPaused=false;this.delegate=null;iAd.Utils.objectIsFunction(a)?this._timerFiredFunction=a:this.delegate=a;this._repeatingTimerPointer=null;this._startTimeOfRepeatingTimer=this._lastScheduledInterval=this._repeatInterval=0};
iAd.Ext.Timer.prototype.startOneShot=function(a){this._isPaused?iAd.Console.error("iAd.Ext.Timer.startOneShot - Timer is paused."):this._timers.push(this._createTimerPointerAndStartTimer(iAd.Ext.Utils.clampNegativeValue(a,iAd.Ext.Timer.MINIMUM_TIMER_INTERVAL)))};
iAd.Ext.Timer.prototype.startRepeating=function(a){this._isPaused?iAd.Console.error("iAd.Ext.Timer.startRepeating - Timer is paused."):(this._repeatingTimerPointer&&this._stopRepeatingTimer(),this._startTimeOfRepeatingTimer=Date.now(),this._lastScheduledInterval=0,this._repeatInterval=iAd.Ext.Utils.clampNegativeValue(a,iAd.Ext.Timer.MINIMUM_TIMER_INTERVAL),this._repeatingTimerPointer=this._createTimerPointerAndStartTimer(this._repeatInterval))};
iAd.Ext.Timer.prototype.repeatInterval=function(){return this._repeatingTimerPointer?this._repeatInterval:0};iAd.Ext.Timer.prototype.isActive=function(){return!this._isPaused&&!(!this._repeatingTimerPointer&&!this._timers.length)};iAd.Ext.Timer.prototype.isPaused=function(){return this._isPaused};iAd.Ext.Timer.prototype.stop=function(){if(!this._isPaused){this._repeatingTimerPointer&&this._stopRepeatingTimer();for(var a in this._timers)window.clearTimeout(this._timers[a].timerId);this._timers=[]}};
iAd.Ext.Timer.prototype.pause=function(){if(!this._isPaused){this._isPaused=true;var a=Date.now();this._repeatingTimerPointer&&this._pauseTimerAtTime(this._repeatingTimerPointer,a);for(var b=0,c=this._timers.length;b<c;++b)this._pauseTimerAtTime(this._timers[b],a)}};iAd.Ext.Timer.prototype.resume=function(){if(this._isPaused){this._isPaused=false;this._repeatingTimerPointer&&this.startRepeating(this._repeatingTimerPointer.interval);var a=this._timers;this._timers=[];for(var b=0,c=a.length;b<c;++b)this.startOneShot(a[b].interval)}};
iAd.Ext.Timer.prototype.restartAllPendingTimers=function(){if(!this._isPaused){var a=this._repeatingTimerPointer,b=this._timers;this.stop();for(var c in b)this.startOneShot(b[c].interval);a&&this.startRepeating(this._repeatInterval)}};iAd.Ext.Timer.prototype._stopRepeatingTimer=function(){window.clearTimeout(this._repeatingTimerPointer.timerId);this._repeatingTimerPointer=null};
iAd.Ext.Timer.prototype._pauseTimerAtTime=function(a,b){window.clearTimeout(a.timerId);var c=b-a.timestamp;a.interval=a.interval>c?a.interval-c:0;a.timerId=null};iAd.Ext.Timer.prototype._createTimerPointerAndStartTimer=function(a){var b={timer:this,timerId:-1,interval:a,timestamp:Date.now()},a=this.callMethodNameAfterDelay("_timerFired",a,b);b.timerId=a;return b};
iAd.Ext.Timer.prototype._computeNextTimeInterval=function(){var a=(Date.now()-this._startTimeOfRepeatingTimer)/1E3,b=this._lastScheduledInterval+this._repeatInterval,c=b+this._repeatInterval;this._lastScheduledInterval=b;return(a>b?(Math.floor(a/this._repeatInterval)+1)*this._repeatInterval:c)-a};
iAd.Ext.Timer.prototype._timerFired=function(a){iAd.Ext.Console.assert(a.timer===this,"timerPointer.timer !== this");iAd.Ext.Console.assert(a.timerId!==-1,"timerPointer.timerId === -1");a!==this._repeatingTimerPointer&&iAd.Array.removeObjectFromArray(a,this._timers);this._timerFiredFunction&&this._timerFiredFunction(this);this.notifyDelegate(iAd.Ext.Timer.TIMER_FIRED_EVENT,this.delegate);if(a===this._repeatingTimerPointer)this._repeatingTimerPointer=this._createTimerPointerAndStartTimer(this._computeNextTimeInterval(a))};
iAd.Ext.Console=iAd.Ext.Console||{};iAd.Ext.Console.assert=iAd.Console.assert||function(){if(window.console&&console.assert)console.assert.apply(console,arguments);else if(!arguments[0])throw"Assertion failed: "+(arguments[1]||"");};iAd.Class({name:"iAd.Ext.ViewControllerTimerStrategyProcessor",synthesizedProperties:["timer","timerStrategy"]});
iAd.Ext.ViewControllerTimerStrategyProcessor.prototype.init=function(a,b,c){this.callSuper();this._viewController=a;this._viewToListenForTouchEvents=c.appliesToRootView?iAd.RootView.sharedRoot:a.view;this._timer=b;this._timerStrategy=c;this._setEnable(true)};iAd.Ext.ViewControllerTimerStrategyProcessor.prototype.setTimerStrategy=function(){};iAd.Ext.ViewControllerTimerStrategyProcessor.prototype.isValid=function(){return this._viewController&&this._timer&&this._timerStrategy};
iAd.Ext.ViewControllerTimerStrategyProcessor.prototype.releaseTimer=function(){this._setEnable(false);var a=this._timer;this._viewToListenForTouchEvents=this._viewController=this._timerStrategy=this._timer=null;return a};
iAd.Ext.ViewControllerTimerStrategyProcessor.prototype.handleEvent=function(a){switch(a.type){case iAd.Event.START_EVENT:this._timerStrategy.handleTouchStart(this,a);return;case iAd.TransitionController.WILL_MAKE_VIEW_CONTROLLER_VISIBLE:a&&a.ad&&a.ad.sender.previouslyVisibleViewController===this._viewController&&this._timerStrategy.handleViewWillDisappear(this,a);return}iAd.Console.error("[iAd.Ext.ViewControllerTimerStrategyProcessor.handleEvent] Should not get here; got event type "+a.type)};
iAd.Ext.ViewControllerTimerStrategyProcessor.prototype._setEnable=function(a){this._viewToListenForTouchEvents[a?"addEventListener":"removeEventListener"](iAd.Event.START_EVENT,this,true);iAd.RootViewController.sharedRootViewController.transitionController[a?"addEventListener":"removeEventListener"](iAd.TransitionController.WILL_MAKE_VIEW_CONTROLLER_VISIBLE,this,false)};iAd.Class({name:"iAd.Ext.MapRegion",synthesizedProperties:["formattedMapRegion"]});
iAd.Ext.MapRegion.prototype.init=function(a,b,c,d){this.callSuper();this._formattedMapRegion=null;this.latitude=a;this.longitude=b;this.latDelta=c;this.longDelta=d};iAd.Ext.MapRegion.prototype.getFormattedMapRegion=function(){return{latitude:this.latitude,longitude:this.longitude,latitudeDelta:this.latDelta,longitudeDelta:this.longDelta}};
iAd.Ext.MapRegion.prototype.equals=function(a){return this.latititude==a.latitude&&this.longitude==a.longitude&&this.latDelta==a.latitudeDelta&&this.longDelta==a.longitudeDelta};iAd.Ext.MapRegion.US=new iAd.Ext.MapRegion(37.33,-100,45,45);
iAd.Ext.MapRegion.regionFromAnnotations=function(a){var b,c,d,e,g=a.length;if(!(g<=0)){b=Number.MAX_VALUE;c=Number.MAX_VALUE;d=-Number.MAX_VALUE;e=-Number.MAX_VALUE;for(var f=0;f<g;f++)b=Math.min(b,a[f].latitude),c=Math.min(c,a[f].longitude),d=Math.max(d,a[f].latitude),e=Math.max(e,a[f].longitude);return new iAd.Ext.MapRegion(b+(d-b)/2,c+(e-c)/2,g>1?(d-b)*1.25:0.08,g>1?(e-c)*1.25:0.08)}};
iAd.Class({name:"iAd.Ext.Map",mixins:[iAd.EventTarget],synthesizedProperties:["mapRegion","mapType","showsUserLocation","hidden","selectedAnnotationId"]});iAd.Ext.Map.CREATE_ANNOTATIONS_METHOD="createCustomizedAnnotation";iAd.Ext.Map.DID_ADD_ANNOTATIONS="mapDidAddViewsForAnnotations";iAd.Ext.Map.DID_UPDATE_USER_LOCATION="mapDidUpdateUserLocation";iAd.Ext.Map.UPDATE_USER_LOCATION_FAILED="mapUpdateUserLocationFailed";iAd.Ext.Map.DID_SELECT_ANNOTATION="mapDidSelectAnnotation";
iAd.Ext.Map.DID_DESELECT_ANNOTATION="mapDidDeselectAnnotation";iAd.Ext.Map.ANNOTATION_LEFT_CALLOUT_TAPPED="mapAnnotationLeftCalloutTapped";iAd.Ext.Map.ANNOTATION_RIGHT_CALLOUT_TAPPED="mapAnnotationRightCalloutTapped";iAd.Ext.Map.REGION_DID_CHANGE="mapRegionDidChange";iAd.Ext.Map.LEGACY_ANNOTATION_CALLOUT_TAPPED="mapAnnotationCalloutTapped";iAd.Ext.Map.SUPPORTS_MAP_PLUGIN=navigator.mimeTypes["application/x-geomap"];iAd.Ext.Map.CSS_CLASS_NAME="ad-ext-map";
iAd.Ext.Map.MAP_TYPES_ENUM={standard:0,satellite:1,hybrid:2,"not-initialized":-1};iAd.Ext.Map.prototype.init=function(){this.callSuper();this._mapRegion=iAd.Ext.MapRegion.US;this._mapType=null;this._showsUserLocation=true;this._hidden=this._mapShouldUpdateAnnotations=this._mapHasBeenShown=false;this.delegate=this._element=this._userLocation=this._selectedAnnotationId=null;this.annotationsArray=[];this.createMap()};
iAd.Ext.Map.prototype.createMap=function(){var a=this._element=document.createElement("object");a.type="application/x-geomap";a.addClassName(iAd.Ext.Map.CSS_CLASS_NAME)};iAd.Ext.Map.prototype.appendMapToView=function(a){a.appendChild(this._element)};
iAd.Ext.Map.prototype.mapWasInsertedIntoDocument=function(){this._element.listener=this;this._element.showsUserLocation=this._showsUserLocation;this._element.mapType=iAd.Ext.Map.MAP_TYPES_ENUM[this._mapType];if(this._mapRegion)this._mapShouldUpdateAnnotations=this.annotationsArray.length>0,this.mapRegion=this._mapRegion};iAd.Ext.Map.prototype.setShowsUserLocation=function(a){if(this._showsUserLocation!=a&&(this._showsUserLocation=a,iAd.Ext.IS_IN_ADSHEET))this._element.showsUserLocation=a};
iAd.Ext.Map.prototype.setSelectedAnnotationId=function(a){if(this._selectedAnnotationId!=a)this._selectedAnnotationId=a};iAd.Ext.Map.prototype.setMapType=function(a){if(this._mapType!=a){var b=iAd.Ext.Map.MAP_TYPES_ENUM.hasOwnProperty(a)?a:"standard";this._element.mapType=iAd.Ext.Map.MAP_TYPES_ENUM[b];this._mapType=b;this._mapType!==a&&iAd.Console.warn("The mapType: "+a+" is not a supported map type. The default mapType will be used")}};
iAd.Ext.Map.prototype.setMapRegion=function(a){this.setMapRegionAnimated(a,true)};iAd.Ext.Map.prototype.setMapRegionAnimated=function(a,b){if(a&&!this._mapRegion.equals(a))this._mapRegion=a,this._element.setRegion(a.formattedMapRegion,b)};iAd.Ext.Map.prototype.setHidden=function(a){this._element.style.visibility=a?"hidden":"visible"};
iAd.Ext.Map.prototype.centerMapByCoordinate=function(a,b){try{this._element.setCenterCoordinate(a,b)}catch(c){iAd.Console.error("iAd.Ext.Map: Unable to center map by coordinate. Error: "+c)}};iAd.Ext.Map.prototype.zoomToAnnotations=function(a,b){this.removeAnnotations();for(var c=0,d=a.length;c<d;c++)this.addAnnotationToArray(this.sanitizeAnnotation(a[c]));this._mapShouldUpdateAnnotations=true;this.setMapRegionAnimated(iAd.Ext.MapRegion.regionFromAnnotations(this.annotationsArray),b)};
iAd.Ext.Map.prototype.sanitizeAnnotation=function(a){return iAd.Ext.MapAnnotation.createAnnotationForMap(a)};iAd.Ext.Map.prototype.addAnnotationToArray=function(a){this.annotationsArray.push(a.formattedAnnotation)};iAd.Ext.Map.prototype.removeAnnotationFromArrayWithId=function(a){for(var b=0,c=this.annotationsArray.length;b<c;b++)if(this.annotationsArray[b].identifier==a)return iAd.Array.removeObjectFromArray(this.annotationsArray[b],this.annotationsArray),true;return false};
iAd.Ext.Map.prototype.addAnnotations=function(a){try{this._element.addAnnotations(a)}catch(b){console.error("iAd.Ext.Map: Unable to add annotations to map. Error: "+b)}};iAd.Ext.Map.prototype.addAnnotation=function(a){try{this._element.addAnnotation(a),this.addAnnotationToArray(this.sanitizeAnnotation(a))}catch(b){console.error("iAd.Ext.Map: Unable to add annotation to map. Error: "+b)}};
iAd.Ext.Map.prototype.removeAnnotations=function(){for(var a=[],b=0,c=this.annotationsArray.length;b<c;b++)a.push(this.annotationsArray[b].identifier);try{this._element.removeAnnotations(a)}catch(d){console.error("iAd.Ext.Map: Unable to remove annotations from map. Error: "+d)}this.annotationsArray=[]};
iAd.Ext.Map.prototype.removeAnnotationWithId=function(a){try{this._element.removeAnnotation(a),this.removeAnnotationFromArrayWithId(a)}catch(b){console.error("iAd.Ext.Map: Unable to remove annotation from map. Error: "+b)}};iAd.Ext.Map.prototype.selectAnnotationWithId=function(a,b){try{this._element.selectAnnotation(a,b)}catch(c){console.error("iAd.Ext.Map: Unable to select annotation with id: "+a+". Error: "+c)}};
iAd.Ext.Map.prototype.deselectAnnotationWithId=function(a){try{this._element.deselectAnnotation(a)}catch(b){console.error("iAd.Ext.Map: Unable to deselect annotation with id: "+a+". Error: "+b)}};iAd.Ext.Map.prototype.mapShouldUpdateLayoutInView=function(){};
iAd.Ext.Map.prototype.mapDidUpdateUserLocation=function(a){if(this._userLocation===null)this.setMapRegionAnimated(new iAd.Ext.MapRegion(a.latitude,a.longitude,5,5),true),this._userLocation=a,this.dispatchNotification(iAd.Ext.Map.DID_UPDATE_USER_LOCATION,this.delegate,[["latitude",a.latitude],["longitude",a.longitude]])};iAd.Ext.Map.prototype.mapDidSelectAnnotation=function(a){this._selectedAnnotationId=a;this.dispatchNotification(iAd.Ext.Map.DID_SELECT_ANNOTATION,this.delegate,[["identifier",a]])};
iAd.Ext.Map.prototype.mapDidDeselectAnnotation=function(a){this._selectedAnnotationId=null;this.dispatchNotification(iAd.Ext.Map.DID_DESELECT_ANNOTATION,this.delegate,[["identifier",a]])};
iAd.Ext.Map.prototype.mapRegionDidChange=function(a){if(this.annotationsArray.length&&this._mapShouldUpdateAnnotations)this.addAnnotations(this.annotationsArray),this._mapShouldUpdateAnnotations=false;this._mapRegion=new iAd.Ext.MapRegion(a.latitude,a.longitude,a.latitudeDelta,a.longitudeDelta);this.dispatchNotification(iAd.Ext.Map.REGION_DID_CHANGE,this.delegate,[["region",a]])};
iAd.Ext.Map.prototype.mapDidAddViewsForAnnotations=function(a){this.dispatchNotification(iAd.Ext.Map.DID_ADD_ANNOTATIONS,this.delegate,[["identifiers",a]])};iAd.Ext.Map.prototype.mapUpdateUserLocationFailed=function(){this.dispatchNotification(iAd.Ext.Map.UPDATE_USER_LOCATION_FAILED,this.delegate)};iAd.Ext.Map.prototype.mapAnnotationLeftCalloutTapped=function(a){this.dispatchNotification(iAd.Ext.Map.ANNOTATION_LEFT_CALLOUT_TAPPED,this.delegate,[["annotationId",a]])};
iAd.Ext.Map.prototype.mapAnnotationRightCalloutTapped=function(a){this.dispatchNotification(iAd.Ext.Map.ANNOTATION_RIGHT_CALLOUT_TAPPED,this.delegate,[["annotationId",a]])};iAd.Ext.Map.mapFactory=function(){return new (!iAd.Ext.IS_IN_ADSHEET?iAd.Ext.OpenLayersMap:iAd.Ext.Map.SUPPORTS_MAP_PLUGIN?iAd.Ext.Map:iAd.Ext.LegacyMap)};iAd.Class({name:"iAd.Ext.MapView",superclass:iAd.View,synthesizedProperties:["showsUserLocation","userLocation","mapRegion","mapType","selectedAnnotationId"],cssClassName:"ad-ext-map-view"});
iAd.Ext.MapView.DID_ADD_ANNOTATIONS="mapViewDidAddViewsForAnnotations";iAd.Ext.MapView.DID_UPDATE_USER_LOCATION="mapViewDidUpdateUserLocation";iAd.Ext.MapView.UPDATE_USER_LOCATION_FAILED="mapViewUpdateUserLocationFailed";iAd.Ext.MapView.DID_SELECT_ANNOTATION="mapViewDidSelectAnnotation";iAd.Ext.MapView.DID_DESELECT_ANNOTATION="mapViewDidDeselectAnnotation";iAd.Ext.MapView.ANNOTATION_LEFT_CALLOUT_TAPPED="mapViewAnnotationLeftCalloutTapped";iAd.Ext.MapView.ANNOTATION_RIGHT_CALLOUT_TAPPED="mapViewAnnotationRightCalloutTapped";
iAd.Ext.MapView.REGION_DID_CHANGE="mapViewRegionDidChange";iAd.Ext.MapView.MAP_TYPE_STANDARD="standard";iAd.Ext.MapView.MAP_TYPE_SATELLITE="satellite";iAd.Ext.MapView.MAP_TYPE_HYBRID="hybrid";iAd.Ext.MapView.MAP_TYPE_NOT_INITIALIZED="not-initialized";
iAd.Ext.MapView.prototype.init=function(a){this._selectedAnnotationId=this._userLocation=this._showsUserLocation=null;this._mapRegion=iAd.Ext.MapRegion.US;this._mapType=iAd.Ext.MapView.MAP_TYPE_STANDARD;this.delegate=null;this._mapHasBeenShown=false;this.callSuper(a)};iAd.Ext.MapView.prototype.layerWasCreated=function(){this.callSuper();if(!this._map)this._map=iAd.Ext.Map.mapFactory(),this._map.delegate=this,this._map.appendMapToView(this.layer)};
iAd.Ext.MapView.prototype.setValueForAttribute=function(a,b){switch(b){case "ad-ext-map-type":this.mapType=a||iAd.Ext.MapView.MAP_TYPE_STANDARD;break;default:this.callSuper(a,b)}};iAd.Ext.MapView.prototype.updatePositionAndTransform=function(){this.callSuper();this.syncMapPositionAndSize()};
iAd.Ext.MapView.prototype.layerWasInsertedIntoDocument=function(){this.callSuper();this.syncMapPositionAndSize();if(!this._mapHasBeenShown)this._map.mapType=this.mapType,this._map.mapRegion=this.mapRegion,this._mapHasBeenShown=true;this._map.mapWasInsertedIntoDocument()};iAd.Ext.MapView.prototype.setShowsUserLocation=function(a){if(this._map)this._map.showsUserLocation=a};iAd.Ext.MapView.prototype.getShowsUserLocation=function(){return this._map?this._map.showsUserLocation:false};
iAd.Ext.MapView.prototype.getUserLocation=function(){return this._map?this._map.userLocation:null};iAd.Ext.MapView.prototype.setMapType=function(a){this._mapType=a;if(this._map)this._map.mapType=a};iAd.Ext.MapView.prototype.getMapType=function(){return this._map?this._map.mapType:iAd.Ext.MapView.MAP_TYPE_NOT_INITIALIZED};iAd.Ext.MapView.prototype.getSelectedAnnotationId=function(){return this._map?this._map.selectedAnnotationId:null};
iAd.Ext.MapView.prototype.setHidden=function(a){this._map.hidden=a;this.callSuper(a)};iAd.Ext.MapView.prototype.setSize=function(a){this.callSuper(a);this.syncMapPositionAndSize()};iAd.Ext.MapView.prototype.setMapRegion=function(a){this.setMapRegionAnimated(a,true)};iAd.Ext.MapView.prototype.setMapRegionAnimated=function(a,b){a&&this._map&&this._map.setMapRegionAnimated(a,b)};iAd.Ext.MapView.prototype.getMapRegion=function(){if(this._map)return this._map.mapRegion};
iAd.Ext.MapView.prototype.syncMapPositionAndSize=function(){this._map&&this._map.mapShouldUpdateLayoutInView(this._size,this._position)};iAd.Ext.MapView.prototype.centerMapByCoordinate=function(a,b){this._map&&this._map.centerMapByCoordinate(a,b===void 0||!!b)};iAd.Ext.MapView.prototype.addAnnotation=function(a){this._map&&this._map.addAnnotation(a)};iAd.Ext.MapView.prototype.zoomToAnnotations=function(a,b){this._map&&this._map.zoomToAnnotations(a,b===void 0||!!b)};
iAd.Ext.MapView.prototype.selectAnnotationWithId=function(a,b){this._map&&this._map.selectAnnotationWithId(a,b===void 0||!!b)};iAd.Ext.MapView.prototype.deselectAnnotationWithId=function(a){this._map&&this._map.deselectAnnotationWithId(a)};iAd.Ext.MapView.prototype.removeAnnotations=function(){this._map&&this._map.removeAnnotations()};iAd.Ext.MapView.prototype.removeAnnotationWithId=function(a){this._map&&this._map.removeAnnotationWithId(a)};
iAd.Ext.MapView.prototype.mapDidUpdateUserLocation=function(a,b,c){this.dispatchNotification(iAd.Ext.MapView.DID_UPDATE_USER_LOCATION,this.delegate,[["latitude",b],["longitude",c]])};iAd.Ext.MapView.prototype.mapDidSelectAnnotation=function(a,b){this.dispatchNotification(iAd.Ext.MapView.DID_SELECT_ANNOTATION,this.delegate,[["identifier",b]])};
iAd.Ext.MapView.prototype.mapDidDeselectAnnotation=function(a,b){this.dispatchNotification(iAd.Ext.MapView.DID_DESELECT_ANNOTATION,this.delegate,[["identifier",b]])};iAd.Ext.MapView.prototype.mapRegionDidChange=function(a,b){this.dispatchNotification(iAd.Ext.MapView.REGION_DID_CHANGE,this.delegate,[["region",b]])};iAd.Ext.MapView.prototype.mapDidAddViewsForAnnotations=function(a,b){this.dispatchNotification(iAd.Ext.MapView.DID_ADD_ANNOTATIONS,this.delegate,[["identifiers",b]])};
iAd.Ext.MapView.prototype.mapUpdateUserLocationFailed=function(){this.dispatchNotification(iAd.Ext.MapView.UPDATE_USER_LOCATION_FAILED,this.delegate)};iAd.Ext.MapView.prototype.mapAnnotationLeftCalloutTapped=function(a,b){this.dispatchNotification(iAd.Ext.MapView.ANNOTATION_LEFT_CALLOUT_TAPPED,this.delegate,[["annotationId",b]])};
iAd.Ext.MapView.prototype.mapAnnotationRightCalloutTapped=function(a,b){this.dispatchNotification(iAd.Ext.MapView.ANNOTATION_RIGHT_CALLOUT_TAPPED,this.delegate,[["annotationId",b]])};iAd.Ext.MediaStrategies={};iAd.Ext.MediaStrategies.IS_WIFI=iAd.Ext.IS_IN_ADSHEET?ad.networkType===ADNetworkTypeListener.kADNetworkTypeListenerNetworkTypeWiFi:true;iAd.Ext.MediaStrategies.WIFI_VIDEO_SUFFIX="_hi";
iAd.Ext.MediaStrategies.defaultLoadReadyStrategy=function(a){return iAd.Ext.MediaStrategies.IS_WIFI?a.canPlay:a.canPlayThrough};iAd.Ext.MediaStrategies.defaultUrlStrategy=function(a){return iAd.Ext.MediaStrategies.IS_WIFI?iAd.Ext.Utils.appendSuffixToPath(a,iAd.Ext.MediaStrategies.WIFI_VIDEO_SUFFIX):a};iAd.Media.loadReadyStrategy=iAd.Ext.MediaStrategies.defaultLoadReadyStrategy;iAd.Media.urlStrategy=iAd.Ext.MediaStrategies.defaultUrlStrategy;
iAd.Class({name:"iAd.Ext.FeedLoader",superclass:iAd.XHRLoader,mixins:[iAd.EventTarget],synthesizedProperties:["useDev","protocolType"]});iAd.Ext.FeedLoader.HTTP_URL_PREFIX="http://";iAd.Ext.FeedLoader.HTTPS_URL_PREFIX="https://";iAd.Ext.FeedLoader.USE_HTTP=false;iAd.Ext.FeedLoader.USE_HTTPS=true;iAd.Ext.FeedLoader.PROD_URL="iadfeed.qwapi.com/feedserverUtils/psFeedHandler.jsp";iAd.Ext.FeedLoader.DEV_URL="psfeed.qwapi.com/feedserverUtils/psFeedHandler.jsp";iAd.Ext.FeedLoader.FORMAT_JSON="json";
iAd.Ext.FeedLoader.FORMAT_XML="xml";iAd.Ext.FeedLoader.FORMAT="format";iAd.Ext.FeedLoader.CLASS="class";iAd.Ext.FeedLoader.METHOD="method";
iAd.Ext.FeedLoader.prototype.init=function(a,b,c,d,e){iAd.Ext.Console.assert(b,"iAd.Ext.FeedLoader.init: Failed to provide method. Was: "+b);iAd.Ext.Console.assert(c,"iAd.Ext.FeedLoader.init: Failed to provide feedFormat. Was: "+c);iAd.Ext.Console.assert(d,"iAd.Ext.FeedLoader.init: Failed to provide feedClassName. Was: "+d);this.params=e?e:{};this.params[iAd.Ext.FeedLoader.METHOD]=b;this.params[iAd.Ext.FeedLoader.FORMAT]=c;this.params[iAd.Ext.FeedLoader.CLASS]=d;this.callSuper("",a,this.params);this.protocolType=
iAd.Ext.FeedLoader.USE_HTTP;this.useDev=false};iAd.Ext.FeedLoader.prototype.setProtocolType=function(a){if(a==iAd.Ext.FeedLoader.USE_HTTPS||a==iAd.Ext.FeedLoader.USE_HTTP)this._protocolType=a};iAd.Ext.FeedLoader.prototype.load=function(){this.url=(this.protocolType?iAd.Ext.FeedLoader.HTTPS_URL_PREFIX:iAd.Ext.FeedLoader.HTTP_URL_PREFIX)+(this.useDev?iAd.Ext.FeedLoader.DEV_URL:iAd.Ext.FeedLoader.PROD_URL);this.callSuper()};iAd.Class({name:"iAd.Ext.LocationLoader",superclass:iAd.Ext.FeedLoader});
iAd.Ext.LocationLoader.ERROR_NO_LOCATIONS=4;iAd.Ext.LocationLoader.ERROR_BAD_DATA=5;iAd.Ext.LocationLoader.CLASS_CALL="com.qwapi.feeds.mongo.StoreLocator";iAd.Ext.LocationLoader.METHOD_CORD_CALL="getStoreLocations";iAd.Ext.LocationLoader.METHOD_ZIP_CALL="getStoreLocationsByZip";iAd.Ext.LocationLoader.LATITUDE="lat";iAd.Ext.LocationLoader.LONGITUDE="lon";iAd.Ext.LocationLoader.ZIP_CODE="zip";iAd.Ext.LocationLoader.RADIUS="radius";iAd.Ext.LocationLoader.MAX="max";iAd.Ext.LocationLoader.SID="sid";
iAd.Ext.LocationLoader.prototype.init=function(a,b,c,d){iAd.Ext.Console.assert(a,"iAd.Ext.LocationLoader.init: Failed to provide SID.");this.zipCode=this.longitude=this.latitude=-1;this.myParams=d?d:{};this.myParams[iAd.Ext.LocationLoader.SID]=a||"demo";this.myParams[iAd.Ext.LocationLoader.RADIUS]=b||100;this.myParams[iAd.Ext.LocationLoader.MAX]=c||10;this.callSuper("GET",iAd.Ext.LocationLoader.METHOD_CORD_CALL,iAd.Ext.FeedLoader.FORMAT_JSON,iAd.Ext.LocationLoader.CLASS_CALL,this.myParams)};
iAd.Ext.LocationLoader.prototype.getLocationsByZip=function(a){iAd.Ext.Console.assert(a,"iAd.Ext.LocationLoader.getLocationsByZip: Failed to provide zipCode.");var b={};iAd.Utils.copyPropertiesFromSourceToTarget(this.myParams,b);b[iAd.Ext.FeedLoader.METHOD]=iAd.Ext.LocationLoader.METHOD_ZIP_CALL;b[iAd.Ext.LocationLoader.ZIP_CODE]=a;this.params=b;this.load()};
iAd.Ext.LocationLoader.prototype.getLocationsByCoordinate=function(a,b){iAd.Ext.Console.assert(a,"iAd.Ext.LocationLoader.getLocationsByCoordinate: Failed to provide latitude.");iAd.Ext.Console.assert(b,"iAd.Ext.LocationLoader.getLocationsByCoordinate: Failed to provide longitude.");var c={};iAd.Utils.copyPropertiesFromSourceToTarget(this.myParams,c);c[iAd.Ext.FeedLoader.METHOD]=iAd.Ext.LocationLoader.METHOD_CORD_CALL;c[iAd.Ext.LocationLoader.LATITUDE]=a;c[iAd.Ext.LocationLoader.LONGITUDE]=b;this.params=
c;this.load()};iAd.Ext.LocationLoader.prototype.notifyLoaderDidComplete=function(){this.loaded=this.loading=false;var a=JSON.parse(this.content);this.zipCode=this.longitude=this.latitude=-1;this.checkDataForErrors(a)?this.dispatchLoaderNotification(iAd.Loader.DID_COMPLETE,[["response",a]]):this.notifyLoaderDidFail(iAd.Ext.LocationLoader.ERROR_NO_LOCATIONS)};
iAd.Ext.LocationLoader.prototype.checkDataForErrors=function(a){if(a)if(!a||!a.length||a.length<=0)return false;else{if(a[0]==="error")return false}else return false;return true};iAd.Ext.Network={};iAd.Ext.Network.NETWORK_UNKNOWN=0;iAd.Ext.Network.NETWORK_GPRS=1;iAd.Ext.Network.NETWORK_EDGE=2;iAd.Ext.Network.NETWORK_3G=3;iAd.Ext.Network.NETWORK_WIFI=4;iAd.Ext.Network.TYPE_DID_CHANGE="networkTypeDidChange";
iAd.Ext.Network.init=function(){iAd.Ext.Network.networkType=iAd.Ext.Network.NETWORK_WIFI;if(iAd.Ext.IS_IN_ADSHEET)window.ad.networkTypeListener=iAd.Ext.Network,iAd.Ext.Network.networkType=window.ad.networkType;iAd.Ext.Network.networkTypeChangeDelegate=null};
iAd.Ext.Network.networkTypeDidChange=function(a){switch(a){case ADNetworkTypeListener.kADNetworkTypeListenerNetworkTypeUnknown:this.networkType=iAd.Ext.Network.NETWORK_UNKNOWN;break;case ADNetworkTypeListener.kADNetworkTypeListenerNetworkTypeGPRS:this.networkType=iAd.Ext.Network.NETWORK_GPRS;break;case ADNetworkTypeListener.kADNetworkTypeListenerNetworkTypeEDGE:this.networkType=iAd.Ext.Network.NETWORK_EDGE;break;case ADNetworkTypeListener.kADNetworkTypeListenerNetworkType3G:this.networkType=iAd.Ext.Network.NETWORK_3G;
break;case ADNetworkTypeListener.kADNetworkTypeListenerNetworkTypeWiFi:this.networkType=iAd.Ext.Network.NETWORK_WIFI;break;default:this.networkType=iAd.Ext.Network.NETWORK_UNKNOWN}if(iAd.Utils.objectHasMethod(this.networkTypeChangeDelegate,iAd.Ext.Network.TYPE_DID_CHANGE))this.networkTypeChangeDelegate[iAd.Ext.Network.TYPE_DID_CHANGE](this.networkType)};window.addEventListener("DOMContentLoaded",iAd.Ext.Network.init,true);
iAd.Class({name:"iAd.Ext.AnalyticsManager",superclass:iAd.Object,synthesizedProperties:["logsToConsole","disableAutomaticEvents","eventDictionary"]});iAd.Ext.AnalyticsManager.prototype.init=function(a){this.callSuper();this.referenceObject=null;this.eventDictionary={};this.rootViewController=a;this.rootViewController.addEventListener(iAd.ViewController.VIEW_DID_APPEAR_EVENT,this,false);this.disableAutomaticEvents=this.logsToConsole=true};
iAd.Ext.AnalyticsManager.prototype.setLogsToConsole=function(a){if(a!=this._logsToConsole)this._logsToConsole=a,iAd.Analytics.logsToConsole=a};iAd.Ext.AnalyticsManager.prototype.setDisableAutomaticEvents=function(a){if(a!=this._disableAutomaticEvents)this._disableAutomaticEvents=a};iAd.Ext.AnalyticsManager.prototype.setEventDictionary=function(a){!a||typeof a!="object"?console.error("[ANALYTICS ERROR]: You must pass in a valid event dictionary."):this._eventDictionary=a};
iAd.Ext.AnalyticsManager.prototype.handleEvent=function(a){!this.disableAutomaticEvents&&a.type==iAd.ViewController.VIEW_DID_APPEAR_EVENT&&(a.ad.sender.id.indexOf("vc-")>-1&&console.warn('[ANALYTICS WARNING]: View controller "'+a.ad.sender.id+'" should have a human readable configuration id.'),iAd.Analytics.log({analyticsObjectId:a.ad.sender.id+"ViewDidAppear",analyticsSectionId:a.ad.sender.id,analyticsType:"view",analyticsName:"viewDidAppear"}))};
iAd.Ext.AnalyticsManager.prototype.verifyReferenceObject=function(a){return a.hasOwnProperty("analyticsObjectId")&&a.hasOwnProperty("analyticsSectionId")&&a.hasOwnProperty("analyticsName")&&a.hasOwnProperty("analyticsType")};iAd.Ext.AnalyticsManager.prototype.stripNullArguments=function(a){a.hasOwnProperty("additionalArguments")&&a.additionalArguments===null&&delete a.additionalArguments;return a};
iAd.Ext.AnalyticsManager.prototype.resolveObjectPath=function(a){if(!(a[0]==="."||a[0]==="")){for(var a=a.split("."),b=this.eventDictionary,c=0,d=a.length;c<d;c++)if(b.hasOwnProperty(a[c]))b=b[a[c]];else return false;return b}};
iAd.Ext.AnalyticsManager.prototype.logMessage=function(a){!a||typeof a!=="string"?console.error("[ANALYTICS ERROR]: a reference object string must be passed in.  Event will not be sent to server."):(this.referenceObject=this.resolveObjectPath(a))?(this.referenceObject=this.stripNullArguments(this.referenceObject),this.verifyReferenceObject(this.referenceObject)?iAd.Analytics.log(this.referenceObject):(console.error("[ANALYTICS ERROR]: Reference event is invalid. Event will not be sent to server."),
console.error("[ANALYTICS ERROR]: Passed reference string",'"'+this.referenceObject+'"')),this.referenceObject=null):console.error("[ANALYTICS ERROR]: Reference object "+this.referenceObject+" not found.  Make sure your string is a valid object path.")};iAd.Class({name:"iAd.Ext.TemplateViewController",superclass:iAd.ViewController,synthesizedProperties:["autoAdvanceAnimates","autoAdvanceDestinationViewController","autoAdvanceTimerStrategy"]});
iAd.Ext.TemplateViewController.prototype.init=function(a){this.callSuper(a);var b=this;this._timer=new iAd.Ext.Timer(function(){b.autoAdvanceTimerFired()});this._timerStrategyProcessor=null;this._autoAdvanceDestinationViewControllerId="";this._autoAdvanceAnimates=true};iAd.Ext.TemplateViewController.prototype.viewDidUnload=function(){this.callSuper();this._timerStrategyProcessor&&this._timerStrategyProcessor.isValid()&&this._timerStrategyProcessor.releaseTimer()};
iAd.Ext.TemplateViewController.prototype.setAutoAdvanceDestinationViewController=function(a){this._autoAdvanceDestinationViewControllerId=a.id};iAd.Ext.TemplateViewController.prototype.getAutoAdvanceDestinationViewController=function(){return adController.viewControllers[this._autoAdvanceDestinationViewControllerId]};iAd.Ext.TemplateViewController.prototype._isAutoAdvanceEnabled=function(){return adController.config.isAutoAdvanceEnabled==void 0||!!adController.config.isAutoAdvanceEnabled};
iAd.Ext.TemplateViewController.prototype.cancelAutoAdvance=function(){this._timer.stop()};iAd.Ext.TemplateViewController.prototype.isActiveAutoAdvanceTimer=function(){return this._timer.isActive()};iAd.Ext.TemplateViewController.prototype.scheduleAutoAdvanceAfterDelay=function(a){this._isAutoAdvanceEnabled()&&(this._timer.stop(),this._timer.startOneShot(a))};
iAd.Ext.TemplateViewController.prototype.setAutoAdvanceTimerStrategy=function(a){if(this._isAutoAdvanceEnabled())a=new iAd.Ext.ViewControllerTimerStrategyProcessor(this,this._timer,a),this._timerStrategyProcessor&&this._timerStrategyProcessor.isValid()&&this._timerStrategyProcessor.releaseTimer(),this._timerStrategyProcessor=a};iAd.Ext.TemplateViewController.prototype.getAutoAdvanceTimerStrategy=function(){return this._timerStrategyProcessor?this._timerStrategyProcessor.timerStrategy:null};
iAd.Ext.TemplateViewController.prototype.autoAdvanceTimerFired=function(){iAd.Ext.Console.assert(this._isAutoAdvanceEnabled(),"iAd.Ext.TemplateViewController.autoAdvanceTimerFired - Auto advance must be enabled");var a=adController.viewControllers[this._autoAdvanceDestinationViewControllerId];a&&adController.showViewController(a,this._autoAdvanceAnimates)};iAd.Class({name:"iAd.Ext.LegacyMapAnnotation",superclass:iAd.Ext.MapAnnotation});
iAd.Ext.LegacyMapAnnotation.prototype.init=function(a){this.callSuper();this._formattedAnnotation=null;this.latitude=a.latitude;this.longitude=a.longitude;this.title=a.title||"";this.subtitle=a.subtitle||"";this.id=a.id.toString();this.imageURL=a.imageURL?iAd.Path.resolveAbsolutePath(iAd.Ext.ASSET_PATH+a.imageURL):null;this.listener=a.listener};
iAd.Ext.LegacyMapAnnotation.prototype.getFormattedAnnotation=function(){return!iAd.Ext.IS_IN_ADSHEET?void 0:new MapAnnotation(this.latitude,this.longitude,this.title,this.subtitle,this.id,this.listener,this.imageURL)};iAd.Class({name:"iAd.Ext.LocalizationViewProcessor",superclass:iAd.ViewProcessor});iAd.Ext.LocalizationViewProcessor.LOCALIZATION_KEY="ad-ext-localization-key";iAd.Ext.LocalizationViewProcessor.prototype.init=function(a){this.callSuper(a);this.processedNodes=[]};
iAd.Ext.LocalizationViewProcessor.prototype.processView=function(a){this.callSuper(a);if(!iAd.Ext.LocalizationViewProcessor._localizationContent||!iAd.Ext.LocalizationViewProcessor._localizationCode)throw Error("Localization: A localization code and a localization content object must be registered.");for(var b=iAd.Ext.LocalizationViewProcessor.LOCALIZATION_KEY,a=a.layer.querySelectorAll("["+(iAd.Element.HTML5_CUSTOM_ATTRIBUTE_PREFIX+b)+"],["+b+"]"),c=iAd.Ext.LocalizationViewProcessor._localizationContent,
d=iAd.Ext.LocalizationViewProcessor._localizationCode,e=0;e<a.length;e++){var g=a[e];if(!g.hasOwnProperty("_adProcessedLocalizedNode")){var f=iAd.Element.getCustomAttribute(g,b);if(c[d].hasOwnProperty(f))g.innerHTML=c[d][f];g._adProcessedLocalizedNode=true;this.processedNodes.push(g)}}};iAd.Ext.LocalizationViewProcessor.registerLocalizationSource=function(a,b){this._localizationCode=a;this._localizationContent=b};
iAd.Ext.LocalizationViewProcessor.prototype.cleanUp=function(){this.callSuper();for(var a;a=this.processedNodes.pop();)delete a._adProcessedLocalizedNode};iAd.Class({name:"iAd.Ext.MediaManager",superclass:iAd.Object});iAd.Ext.MediaManager.IS_PRELOADED="mediaCanPlayThrough";iAd.Ext.MediaManager.IS_PLAYING="mediaIsPlaying";iAd.Ext.MediaManager.IS_PAUSED="mediaWasPaused";iAd.Ext.MediaManager.IS_SEEKING="mediaIsSeeking";iAd.Ext.MediaManager.HAS_ENDED="mediaHasEnded";iAd.Ext.MediaManager.HAS_CLOSED="mediaHasClosed";
iAd.Ext.MediaManager.IS_READY="mediaIsReady";iAd.Ext.MediaManager.CAN_PLAY="mediaCanPlay";iAd.Ext.MediaManager.TIME_UPDATE="mediaTimeUpdate";iAd.Ext.MediaManager.HAS_PLAYED_25_PERCENT="mediaHasPlayed25Percent";iAd.Ext.MediaManager.HAS_PLAYED_50_PERCENT="mediaHasPlayed50Percent";iAd.Ext.MediaManager.HAS_PLAYED_75_PERCENT="mediaHasPlayed75Percent";iAd.Ext.MediaManager.IPHONE_DIR="assets/iphone/videos/";iAd.Ext.MediaManager.IPAD_DIR="assets/ipad/videos/";iAd.Ext.MediaManager.EVENTS="ended,canplaythrough,canplay,loadedmetadata,webkitendfullscreen,pause,play,timeupdate".split(",");
iAd.Ext.MediaManager.prototype.init=function(a){this.callSuper();this.video=this.audio=null;this.recTags=a||true;this.isInline=false;this.delegate=null;this.layerHolder=iAd.RootView.sharedRoot.layer;this.progressMilestones=[25,50,75];this.progressIncrement=25;this.videoObservers=[];this.videoControls=null};
iAd.Ext.MediaManager.prototype.createElement=function(a,b){var c=document.createElement(a);c.id="ad-ext-"+a;b?b.appendChild(c):iAd.RootView.sharedRoot.layer.appendChild(c);this.createListeners(c);return c};iAd.Ext.MediaManager.prototype.removeElement=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};iAd.Ext.MediaManager.prototype.exitFullScreen=function(a,b){var c=this;setTimeout(function(){c.removeElement(a)},b||500)};
iAd.Ext.MediaManager.prototype.preloadElement=function(a){a.load();iAd.Device.iOSVersionLessThan("4.3")&&(a.play(),a.pause())};iAd.Ext.MediaManager.prototype.createListeners=function(a){for(var b=iAd.Ext.MediaManager.EVENTS.length,c=0;c<b;c++)a.addEventListener(iAd.Ext.MediaManager.EVENTS[c],this,false)};
iAd.Ext.MediaManager.prototype.removeEventListeners=function(a){if(!a)return false;for(var b=iAd.Ext.MediaManager.EVENTS.length,c=0;c<b;c++)console.log(a),a.removeEventListener(iAd.Ext.MediaManager.EVENTS[c],this,false)};iAd.Ext.MediaManager.prototype.delegateCallback=function(a){if(iAd.Utils.objectHasMethod(this.delegate,a)){var b=Array.prototype.slice.call(arguments,1);b.unshift(this);this.delegate[a].apply(this.delegate,b)}};
iAd.Ext.MediaManager.prototype.handleEvent=function(a){this[a.type+"Callback"](a.target);for(var b=this.videoObservers.length,c=0;c<b;c++)this.videoObservers[c].handleEvent(a)};iAd.Ext.MediaManager.prototype.endedCallback=function(a){this.resetProgressMilestones(a);!this.isInline&&a.id!=="ad-ext-audio"&&a.webkitExitFullScreen();document.querySelector("body").removeClassName("video-playing");this.delegateCallback(iAd.Ext.MediaManager.HAS_ENDED)};
iAd.Ext.MediaManager.prototype.registerVideoObserver=function(a){a&&this.video&&this.videoObservers.push(a)};iAd.Ext.MediaManager.prototype.canplaythroughCallback=function(){this.delegateCallback(iAd.Ext.MediaManager.IS_PRELOADED);this.isWifi()||this.delegateCallback(iAd.Ext.MediaManager.IS_READY)};iAd.Ext.MediaManager.prototype.canplayCallback=function(){this.isWifi()&&this.delegateCallback(iAd.Ext.MediaManager.IS_READY);this.delegateCallback(iAd.Ext.MediaManager.CAN_PLAY)};
iAd.Ext.MediaManager.prototype.loadedmetadataCallback=function(a){this.isPreloaded&&a.pause()};iAd.Ext.MediaManager.prototype.webkitendfullscreenCallback=function(a){!this.isInline&&a.id!=="ad-ext-audio"&&this.exitFullScreen(a);this.delegateCallback(iAd.Ext.MediaManager.HAS_CLOSED)};iAd.Ext.MediaManager.prototype.pauseCallback=function(){this.delegateCallback(iAd.Ext.MediaManager.IS_PAUSED)};iAd.Ext.MediaManager.prototype.playCallback=function(){this.delegateCallback(iAd.Ext.MediaManager.IS_PLAYING)};
iAd.Ext.MediaManager.prototype.timeupdateCallback=function(a){this.delegateCallback(iAd.Ext.MediaManager.TIME_UPDATE,a.currentTime);this.detectPercentagePlayed(a)};
iAd.Ext.MediaManager.prototype.createVideoTag=function(a,b){this.layerHolder=b?b:this.layerHolder;if(!this.video||!this.video.parentNode)this.video=this.createElement("video",this.layerHolder);else if(this.recTags&&this.video.src!=a&&a!="")this.removeElement(this.video),this.video=this.createElement("video",this.layerHolder);if(!this.audio)this.audio=this.createElement("audio")};
iAd.Ext.MediaManager.prototype.isWifi=function(){return(iAd.Ext.IS_IN_ADSHEET?ad.networkType:iAd.Ext.Network.NETWORK_WIFI)==iAd.Ext.Network.NETWORK_WIFI};iAd.Ext.MediaManager.prototype.setVideoSource=function(a){return a};iAd.Ext.MediaManager.prototype.detectPercentagePlayed=function(a){var a=a.currentTime/a.duration*100,b=Math.floor(a/this.progressIncrement)-1,c=this.progressMilestones[b];c&&a>=c&&(this.delegateCallback("mediaHasPlayed"+c+"Percent"),this.progressMilestones[b]=null)};
iAd.Ext.MediaManager.prototype.resetProgressMilestones=function(){this.progressMilestones=[25,50,75]};
iAd.Ext.MediaManager.prototype.setVideo=function(a,b,c,d){this.removeEventListeners(this.video);this.removeEventListeners(this.audio);this.resetProgressMilestones();c==void 0&&(c=true);b==void 0&&(b=true);this.isInline=b;this.isPreloaded=c;this.createVideoTag(a,d?d:iAd.RootView.sharedRoot.layer);this.isInline?(this.video.setAttribute("webkit-playsinline","true"),this.video.addClassName("inline-video")):this.video.addClassName("fullscreen-video");this.recTags&&a!=this.video.src&&(this.video.setAttribute("src",
this.setVideoSource(a)),c&&this.preloadElement(this.video))};iAd.Ext.MediaManager.prototype.setInlineVideo=function(a,b){this.setVideo(a,true,true,b)};iAd.Ext.MediaManager.prototype.setFullScreenVideo=function(a){this.playFullScreenVideo(a)};
iAd.Ext.MediaManager.prototype.setAudio=function(a){this.removeEventListeners(this.video);this.removeEventListeners(this.audio);this.resetProgressMilestones();if(this.audio){if(this.recTags&&this.audio.src!=a)this.removeElement(this.audio),this.audio=this.createElement("audio")}else this.audio=this.createElement("audio");if(this.audio.src!=a)this.audio.src=a,this.preloadElement(this.audio)};iAd.Ext.MediaManager.prototype.getAudio=function(){return this.audio};
iAd.Ext.MediaManager.prototype.getVideo=function(){return this.video};iAd.Ext.MediaManager.prototype.playVideo=function(a,b,c){a&&this.setVideo(a,b,false,c);this.getVideo().play();document.querySelector("body").addClassName("video-playing")};iAd.Ext.MediaManager.prototype.playInlineVideo=function(){this.playVideo()};iAd.Ext.MediaManager.prototype.playFullScreenVideo=function(a){this.playVideo(a,false)};
iAd.Ext.MediaManager.prototype.pauseVideo=function(){var a=this.getVideo();a?a.pause():console.log("No Video to Pause");document.querySelector("body").removeClassName("video-playing")};iAd.Ext.MediaManager.prototype.playAudio=function(a){a&&this.setAudio(a);this.getAudio().play()};iAd.Ext.MediaManager.prototype.pauseAudio=function(){var a=this.getAudio();a?a.pause():console.log("No Audio to Pause")};
iAd.Class({name:"iAd.Ext.OpenLayersMap",mixins:[iAd.EventTarget],synthesizedProperties:["mapRegion","mapType","showsUserLocation"]});iAd.Ext.OpenLayersMap.DID_ADD_ANNOTATIONS="mapDidAddViewsForAnnotations";iAd.Ext.OpenLayersMap.DID_UPDATE_USER_LOCATION="mapDidUpdateUserLocation";iAd.Ext.OpenLayersMap.UPDATE_USER_LOCATION_FAILED="mapUpdateUserLocationFailed";iAd.Ext.OpenLayersMap.DID_SELECT_ANNOTATION="mapDidSelectAnnotation";iAd.Ext.OpenLayersMap.DID_DESELECT_ANNOTATION="mapDidDeselectAnnotation";
iAd.Ext.OpenLayersMap.ANNOTATION_LEFT_CALLOUT_TAPPED="mapAnnotationLeftCalloutTapped";iAd.Ext.OpenLayersMap.ANNOTATION_RIGHT_CALLOUT_TAPPED="mapAnnotationRightCalloutTapped";iAd.Ext.OpenLayersMap.REGION_DID_CHANGE="mapRegionDidChange";iAd.Ext.OpenLayersMap.OPEN_LAYERS_URL="http://openlayers.org/api/OpenLayers.js";iAd.Ext.OpenLayersMap.IDENTIFIER="MapShimLayer";iAd.Ext.OpenLayersMap.CSS_CLASS_NAME="ad-ext-map";iAd.Ext.OpenLayersMap.INFO_BUTTON_URL="iAd/assets/ext/infoIcon.png";
iAd.Ext.OpenLayersMap.ARROW_BUTTON_URL="iAd/assets/ext/arrowIcon.png";iAd.Ext.OpenLayersMap.DEFAULT_MARKER_ICON="iAd/assets/ext/redPin.png";iAd.Ext.OpenLayersMap.DEFAULT_MARKER_ICON_SIZE={width:23,height:44};iAd.Ext.OpenLayersMap.USER_LOCATION_ICON="iAd/assets/ext/blueDot.png";iAd.Ext.OpenLayersMap.USER_LOCATION_ICON_SIZE={width:29,height:29};iAd.Ext.OpenLayersMap.DEFAULT_ZOOM_LEVEL=2;iAd.Ext.OpenLayersMap.USER_LOCATION_ZOOM_LEVEL=10;
iAd.Ext.OpenLayersMap.prototype.init=function(){this.callSuper();this._mapRegion=iAd.Ext.MapRegion.US;this._showsUserLocation=false;this._element=null;this.annotationsArray=[];this.featureIdArray=[];this._mapViewLayerHasBeenAppendedToView=this._openLayersLoaded=false;this._popupContext=this._userLocation=this._layer=null;this._isMapSetUp=false;this.loadMapScript()};
iAd.Ext.OpenLayersMap.prototype.loadMapScript=function(){this.loader=new iAd.ScriptLoader(iAd.Ext.OpenLayersMap.OPEN_LAYERS_URL);this.loader.delegate=this;this.loader.load()};iAd.Ext.OpenLayersMap.prototype.loaderDidComplete=function(){this._openLayersLoaded=true;this._mapViewLayerHasBeenAppendedToView||this.createMap()};iAd.Ext.OpenLayersMap.prototype.appendMapToView=function(a){this._layer=a;this.createMap()};iAd.Ext.OpenLayersMap.prototype.mapShouldUpdateLayoutInView=function(){};
iAd.Ext.OpenLayersMap.prototype.mapWasInsertedIntoDocument=function(){};
iAd.Ext.OpenLayersMap.prototype.createMap=function(){if(this._openLayersLoaded&&this._layer)this._mapViewLayerHasBeenAppendedToView=true,this._layer.id=iAd.Ext.OpenLayersMap.IDENTIFIER,this._element=new OpenLayers.Map(iAd.Ext.OpenLayersMap.IDENTIFIER,{controls:[new OpenLayers.Control.Navigation,new OpenLayers.Control.ArgParser,new OpenLayers.Control.Attribution]}),this.userLocationLayer=new OpenLayers.Layer.Markers("userLocationLayer"),this.markersLayer=new OpenLayers.Layer.Markers("markerLayer"),
this._element.addLayers([new OpenLayers.Layer.OSM({sphericalMercator:true}),this.userLocationLayer,this.markersLayer]),this._isMapSetUp=true,this.setMapRegionAnimated(this._mapRegion),this.createGelocationContols()};iAd.Ext.OpenLayersMap.prototype._transformProjectionLonLat=function(a,b){var c=new OpenLayers.Projection("EPSG:4326"),d=new OpenLayers.Projection("EPSG:900913");return(new OpenLayers.LonLat(a,b)).transform(c,d)};
iAd.Ext.OpenLayersMap.prototype.createGelocationContols=function(){this.geolocate=new OpenLayers.Control.Geolocate({bind:false,geolocationOptions:{enableHighAccuracy:false,maximumAge:0,timeout:3E4}});this._element.addControl(this.geolocate);this.geolocate.mapBrowserShimContext=this;this.geolocate.events.register("locationupdated",this.geolocate,iAd.Ext.OpenLayersMap.userLocationUpdated);this.geolocate.events.register("locationfailed",this.geolocate,iAd.Ext.OpenLayersMap.userLocationUpdateFailed);
this.geolocate.events.register("locationuncapable",this.geolocate,iAd.Ext.OpenLayersMap.userLocationUncapable);this.showsUserLocation=true};
iAd.Ext.OpenLayersMap.userLocationUpdated=function(a){var b=a.position.coords.latitude,a=a.position.coords.longitude,c=this.mapBrowserShimContext._transformProjectionLonLat(a,b);this.mapBrowserShimContext._element.setCenter(c,iAd.Ext.OpenLayersMap.USER_LOCATION_ZOOM_LEVEL);c=new OpenLayers.Marker(c);c.icon=new OpenLayers.Icon(iAd.Ext.OpenLayersMap.USER_LOCATION_ICON,new OpenLayers.Size(iAd.Ext.OpenLayersMap.USER_LOCATION_ICON_SIZE.width,iAd.Ext.OpenLayersMap.USER_LOCATION_ICON_SIZE.height));this.mapBrowserShimContext.userLocationLayer.addMarker(c);
this.mapBrowserShimContext._userLocation={latitude:b,longitude:a};this.mapBrowserShimContext.dispatchNotification(iAd.Ext.OpenLayersMap.DID_UPDATE_USER_LOCATION,this.mapBrowserShimContext.delegate,[["latitude",b],["longitude",a]])};iAd.Ext.OpenLayersMap.userLocationUpdateFailed=function(){this.mapBrowserShimContext.dispatchNotification(iAd.Ext.OpenLayersMap.UPDATE_USER_LOCATION_FAILED,this.mapBrowserShimContext.delegate);iAd.Console.warn("iAd.Ext.OpenLayersMap: You must enable Geolocation.")};
iAd.Ext.OpenLayersMap.userLocationUncapable=function(){this.userLocationUpdateFailed()};iAd.Ext.OpenLayersMap.prototype.setShowsUserLocation=function(a){if(this._showsUserLocation!=a&&this.geolocate)this.userLocation||this.geolocate.activate(),this.userLocationLayer&&this.userLocationLayer.setOpacity(a+0),this._showsUserLocation=a};iAd.Ext.OpenLayersMap.prototype.setMapType=function(a){this._mapType=a;iAd.Console.warn("iAd.Ext.OpenLayersMap: Changing the mapType property is not available in the browser.")};
iAd.Ext.OpenLayersMap.prototype.setSelectedAnnotationId=function(a){this._selectedAnnotationId=a};iAd.Ext.OpenLayersMap.prototype.setMapRegion=function(a){this.setMapRegionAnimated(a,true)};
iAd.Ext.OpenLayersMap.prototype.setMapRegionAnimated=function(a,b){if(a&&!this._mapRegion.equals(a)&&this._isMapSetUp)this._mapRegion=a,this._shouldMapAquireRegionFromAnnotations?this._element.zoomToExtent(this.markersLayer.getDataExtent()):this._element.setCenter(this._transformProjectionLonLat(a.longitude,a.latitude),iAd.Ext.OpenLayersMap.DEFAULT_ZOOM_LEVEL),this.dispatchNotification(iAd.Ext.OpenLayersMap.REGION_DID_CHANGE,this.delegate,[["region",a]]),iAd.Console.warn("iAd.Ext.OpenLayersMap: Then animated flag for setMapRegionAnimated is set to: "+
b+". Zoom animation on region changes is not supported in the browser.")};iAd.Ext.OpenLayersMap.prototype.centerMapByCoordinate=function(a,b){this._element.setCenter(this._transformProjectionLonLat(a.longitude,a.latitude));iAd.Console.warn("iAd.Ext.OpenLayersMap: Then animated argument in the centerMapByCoordinate() is set to: "+b+". Zoom animation on region changes is not supported in the browser.")};iAd.Ext.OpenLayersMap.prototype.addAnnotationToArray=function(a){this.annotationsArray.push(a.formattedAnnotation)};
iAd.Ext.OpenLayersMap.prototype.emptyAnnotationsArray=function(){this.annotationsArray=[]};iAd.Ext.OpenLayersMap.prototype.sanitizeAnnotation=function(a){return iAd.Ext.MapAnnotation.createAnnotationForMap(a)};
iAd.Ext.OpenLayersMap.prototype.zoomToAnnotations=function(a,b){this.removeAnnotations();for(var c;annotation=a.pop();)c=this.sanitizeAnnotation(annotation),this.addAnnotationToArray(c),this.addAnnotation(c.formattedAnnotation);this._shouldMapNotifyUpdateAnnotations=false;this._shouldMapAquireRegionFromAnnotations=true;this.setMapRegionAnimated(iAd.Ext.MapRegion.regionFromAnnotations(this.annotationsArray),b);this.notifyMapDidUpdateAnnotations()};
iAd.Ext.OpenLayersMap.prototype.addAnnotation=function(a){var b=this._transformProjectionLonLat(a.longitude,a.latitude),c={};c.popupContentHTML=this.createAnnotationMarkup(a);c.overflow="hidden";c.icon=a.imageURL?new OpenLayers.Icon(a.imageURL,""):new OpenLayers.Icon(iAd.Ext.OpenLayersMap.DEFAULT_MARKER_ICON,new OpenLayers.Size(iAd.Ext.OpenLayersMap.DEFAULT_MARKER_ICON_SIZE.width,iAd.Ext.OpenLayersMap.DEFAULT_MARKER_ICON_SIZE.height));b=new OpenLayers.Feature(this.markersLayer,b,c);b.popupClass=OpenLayers.Popup.FramedCloud;
b.mapBrowserShimContext=this;b.identifier=a.identifier;b.hasLeftCallout=a.hasLeftCalloutButton;b.hasRightCallout=a.hasRightCalloutButton;this.featureIdArray.push(b.identifier);c=b.createMarker();c.events.register("click",b,iAd.Ext.OpenLayersMap.handleMarkerClick);this.markersLayer.addMarker(c);c.identifier=a.identifier;this._shouldMapNotifyUpdateAnnotations&&this.notifyMapDidUpdateAnnotations()};iAd.Ext.OpenLayersMap._escapeHTML=function(a){var b=document.createElement("div");b.innerText=a;return b.innerHTML};
iAd.Ext.OpenLayersMap.prototype.createAnnotationMarkup=function(a){var b=a.hasLeftCalloutButton,c=a.hasRightCalloutButton,d=b?" leftCallout":"";d+=c?" rightCallout":"";d='<div class = "browserShimPopupContent'+d+'">';d+="<h2>"+iAd.Ext.OpenLayersMap._escapeHTML(a.title)+"</h2>";d+="<p>"+iAd.Ext.OpenLayersMap._escapeHTML(a.subtitle)+"</p>";b&&(d+='<img class="leftCalloutButton" identifier="'+a.identifier+'" src="'+iAd.Ext.OpenLayersMap.INFO_BUTTON_URL+'">');c&&(d+='<img class="rightCalloutButton" identifier="'+
a.identifier+'" src="'+iAd.Ext.OpenLayersMap.ARROW_BUTTON_URL+'">');d+="</div>";return d};iAd.Ext.OpenLayersMap.prototype.selectAnnotationWithId=function(a){(a=this.objectFromArrayById(this.markersLayer.markers,a))&&a.events.triggerEvent("click")};iAd.Ext.OpenLayersMap.prototype.deselectAnnotationWithId=function(a){this.emptyPopups();this.dispatchNotification(iAd.Ext.OpenLayersMap.DID_DESELECT_ANNOTATION,this.delegate,[["identifier",a]]);this.selectedAnnotationId=null};
iAd.Ext.OpenLayersMap.prototype.removeAnnotationWithId=function(a){(a=this.objectFromArrayById(this.markersLayer.markers,a))&&this.markersLayer.removeMarker(a)};iAd.Ext.OpenLayersMap.prototype.removeAnnotations=function(){this.markersLayer.clearMarkers();this.featureIdArray=[];this.emptyAnnotationsArray();this.emptyPopups()};
iAd.Ext.OpenLayersMap.prototype.emptyPopups=function(){if(this._popupContext){for(var a=this._popupContext.layer.map,b=0,c=a.popups.length;b<c;b++)a.removePopup(a.popups[b]);this.selectedAnnotationId=null}};iAd.Ext.OpenLayersMap.prototype.objectFromArrayById=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];if(e&&e.identifier==b)return e}return false};
iAd.Ext.OpenLayersMap.prototype.notifyMapDidUpdateAnnotations=function(){this.dispatchNotification(iAd.Ext.OpenLayersMap.DID_ADD_ANNOTATIONS,this.delegate,[["identifiers",this.featureIdArray]]);this._shouldMapNotifyUpdateAnnotations=false;this._shouldMapAquireRegionFromAnnotations=true;this.emptyAnnotationsArray()};
iAd.Ext.OpenLayersMap.handleMarkerClick=function(){var a=this==this.layer.selectedFeature;this.layer.selectedFeature=a?null:this;this.mapBrowserShimContext._popupContext=this;for(var b=0,c=this.layer.map.popups.length;b<c;b++)this.layer.map.removePopup(this.layer.map.popups[b]);if(!a){a=this.createPopup();a.identifier=this.identifier;this.mapBrowserShimContext.selectedAnnotationId=this.identifier;OpenLayers.Event.observe(a.div,"click",OpenLayers.Function.bind(function(a){a=a.target;!a.hasClassName("leftCalloutButton")&&
!a.hasClassName("rightCalloutButton")&&(this.mapBrowserShimContext.deselectAnnotationWithId(this.identifier),this.hasLeftCallout&&d.removeEventListener("click",this.mapBrowserShimContext,true),this.hasRightCallout&&e.removeEventListener("click",this.mapBrowserShimContext,true))},this));this.layer.map.addPopup(a);if(this.hasLeftCallout){var d=this.popup.contentDiv.querySelector(".leftCalloutButton");d.addEventListener("click",this.mapBrowserShimContext,true)}if(this.hasRightCallout){var e=this.popup.contentDiv.querySelector(".rightCalloutButton");
e.addEventListener("click",this.mapBrowserShimContext,true)}this.mapBrowserShimContext.dispatchNotification(iAd.Ext.OpenLayersMap.DID_SELECT_ANNOTATION,this.mapBrowserShimContext.delegate,[["identifier",this.identifier]])}};
iAd.Ext.OpenLayersMap.prototype.handleEvent=function(a){var b=a.target;a.type==="click"&&b.getAttribute("identifier")&&(a=b.hasClassName("leftCalloutButton")?iAd.Ext.OpenLayersMap.ANNOTATION_LEFT_CALLOUT_TAPPED:iAd.Ext.OpenLayersMap.ANNOTATION_RIGHT_CALLOUT_TAPPED,b=b.getAttribute("identifier"),this.dispatchNotification(a,this.delegate,[["annotationId",b]]))};iAd.Class({name:"iAd.Ext.LegacyMap",superclass:iAd.Ext.Map});iAd.Ext.LegacyMap.LEGACY_ANNOTATION_CALLOUT_TAPPED="mapAnnotationCalloutTapped";
iAd.Ext.LegacyMap.prototype.init=function(){this.callSuper();this._mapHasBeenShown=false};iAd.Ext.LegacyMap.prototype.createMap=function(){if(iAd.Ext.IS_IN_ADSHEET)this._element=ad.map};iAd.Ext.LegacyMap.prototype.appendMapToView=function(){};iAd.Ext.LegacyMap.prototype.mapWasInsertedIntoDocument=function(){if(iAd.Ext.IS_IN_ADSHEET)this._element.listener=this,this.hidden=false,this._element.showsUserLocation=this._showsUserLocation};
iAd.Ext.LegacyMap.prototype.setMapRegion=function(a){this._mapRegion!=a&&this.setMapRegionAnimated(a.formattedMapRegion)};iAd.Ext.LegacyMap.prototype.setMapRegionAnimated=function(a){if(iAd.Ext.IS_IN_ADSHEET)this._mapRegion=a,this._element.region=a};iAd.Ext.LegacyMap.prototype.setMapType=function(){};iAd.Ext.LegacyMap.prototype.setHidden=function(a){if(iAd.Ext.IS_IN_ADSHEET)this._element.hidden=a?true:false};
iAd.Ext.LegacyMap.prototype.sanitizeAnnotation=function(a){return iAd.Ext.MapAnnotation.createAnnotationForMap({latitude:a.latitude,longitude:a.longitude,id:a.identifier,title:a.title,subtitle:a.subtitle,listener:this,imageURL:a.imageURL})};iAd.Ext.LegacyMap.prototype.zoomToAnnotations=function(a){this.removeAnnotations();for(var b=0,c=a.length;b<c;b++)this.addAnnotationToArray(this.sanitizeAnnotation(a[b]));this._element.addAnnotations(this.annotationsArray);this.mapRegion=iAd.Ext.MapRegion.regionFromAnnotations(this.annotationsArray)};
iAd.Ext.LegacyMap.prototype.removeAnnotations=function(){if(this.annotationsArray.length)for(;this.annotationsArray.length>0;)this._element.removeAnnotation(this.annotationsArray.pop().identifier);this.annotationsArray=[]};iAd.Ext.LegacyMap.prototype.mapShouldUpdateLayoutInView=function(a,b){if(iAd.Ext.IS_IN_ADSHEET)this._element.frame=new MapRect(b.x,b.y,a.width,a.height)};iAd.Ext.LegacyMap.prototype.mapRegionDidChange=function(){};iAd.Ext.LegacyMap.prototype.mapAnnotationCalloutTapped=function(a){this.mapAnnotationLeftCalloutTapped(a)};
iAd.Class({name:"iAd.Ext.AdController",superclass:iAd.RootViewController});iAd.Ext.AdController.LOADING_CSS_CLASS_NAME="ad-ext-loading";
iAd.Ext.AdController.prototype.init=function(a){this.callSuper();this.localizationContent=a.localizationContent;this.config=a.config;this.viewControllers=iAd.ViewController.instances;this.analytics=new iAd.Ext.AnalyticsManager(this);this.localization=null;this.config.isConsoleLoggingEnabled===void 0||this.config.isConsoleLoggingEnabled||this._disableConsoleLogging();this.config.versionCode&&document.body.addClassName(this.config.versionCode);!iAd.Ext.IS_IN_ADSHEET&&this.config.isiPad&&this.forceIsiPad();
!iAd.Ext.IS_IN_ADSHEET&&this.config.isLandscape&&this.forceLandscape();this.config.locale&&this.localizationContent&&this.setupLocalization(this.config.locale,this.localizationContent);iAd.Device.IS_IPAD||document.body.addClassName("ad-iPhone");if(a.analyticsEvents)this.analytics.eventDictionary=a.analyticsEvents;this.callMethodNameAfterDelay("didCompleteSetup",0)};
iAd.Ext.AdController.prototype.createViewController=function(a,b,c){c.id=b;iAd.Ext.Console.assert(!this.viewControllers[b],"[iAd.Ext.AdController] View Controller with duplicate id created: "+b);return new a(c)};iAd.Ext.AdController.prototype.loadViewController=function(a,b){a.requiredFilesLoadDelegate=b||this;a.loadRequiredFiles()};
iAd.Ext.AdController.prototype.showViewController=function(a,b){var c;a!==this.transitionController.visibleViewController&&this.transitionController.setVisibleViewControllerAnimated(a,b!==void 0?b:true)};iAd.Ext.AdController.prototype.cacheViewController=function(a){for(var b=this.transitionController.cachedViewControllers||[],c=0,d=b.length;c<d;c++)if(view_controller===b[c])return;this.transitionController.cachedViewControllers=b.concat([a])};
iAd.Ext.AdController.prototype.uncacheViewController=function(){for(var a=this.transitionController.cachedViewControllers,b=0,c=a.length;b<c;b++)if(view_controller===a[b]){this.transitionController.cachedViewControllers=a.splice(b,1);break}};iAd.Ext.AdController.prototype.addSubviewToRoot=function(a){this.view.addSubview(a)};iAd.Ext.AdController.prototype.showLoadingIndicator=function(){iAd.RootView.sharedRoot.layer.addClassName(iAd.Ext.AdController.LOADING_CSS_CLASS_NAME)};
iAd.Ext.AdController.prototype.hideLoadingIndicator=function(){iAd.RootView.sharedRoot.layer.removeClassName(iAd.Ext.AdController.LOADING_CSS_CLASS_NAME)};iAd.Ext.AdController.prototype.didCompleteSetup=function(){};iAd.Ext.AdController.prototype.transitionControllerDidMakeViewControllerVisibleAnimated=function(a,b){var c=b.configuration.shouldAutoHideLoadingIndicator;(c==void 0||c)&&this.hideLoadingIndicator()};
iAd.Ext.AdController.prototype.setupLocalization=function(a,b){document.body.addClassName(a);b.iPhone&&!iAd.Device.IS_IPAD?b=b.iPhone:b.iPad&&iAd.Device.IS_IPAD?b=b.iPad:(b.iPhone||b.iPad)&&console.warn("[iAd.Ext.AdController] Localized content for device missing!");iAd.ViewController.addViewProcessor(iAd.Ext.LocalizationViewProcessor);iAd.Ext.LocalizationViewProcessor.registerLocalizationSource(a,b)};
iAd.Ext.AdController.prototype.forceIsiPad=function(){iAd.Device.IS_IPAD=true;document.body.addClassName("ad-iPad");iAd.Ext.DEVICE_PATH=iAd.Device.IS_IPAD?"ipad/":"iphone/";iAd.Ext.CSS_PATH="css/"+iAd.Ext.DEVICE_PATH;iAd.Ext.ASSET_PATH="assets/"+iAd.Ext.DEVICE_PATH};iAd.Ext.AdController.prototype.forceLandscape=function(){iAd.Device.setInterfaceOrientation(iAd.Device.ORIENTATION_LANDSCAPE_LEFT)};
iAd.Ext.AdController.prototype._disableConsoleLogging=function(){var a=function(){},b=Object.getPrototypeOf(console);for(n in b)console[n]=a};
